services:
  razzmatazz:
    image: ghcr.io/all-english/razzmatazz:latest
    container_name: razzmatazz
    restart: unless-stopped
    init: true
    ports:
      - "3050:3000"
    volumes:
      - ./config:/app/config
    # environment:
    #   - APP_DOMAIN=https://razzmatazz.example.com
