services:
  razzmatazz:
    build: .
    container_name: razzmatazz
    restart: unless-stopped
    init: true
    ports:
      - "3050:3000"
    volumes:
      - ./config:/app/config
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-https://www.myapp.com}
