export const EVENTS = {
  GAME: {
    STATUS: "game:status",
    SUCCESS_ROOM: "game:successRoom",
    SUCCESS_JOIN: "game:successJoin",
    TOTAL_PLAYERS: "game:totalPlayers",
    ERROR_MESSAGE: "game:errorMessage",
    START_COOLDOWN: "game:startCooldown",
    COOLDOWN: "game:cooldown",
    RESET: "game:reset",
    UPDATE_QUESTION: "game:updateQuestion",
    PLAYER_ANSWER: "game:playerAnswer",
    CREATE: "game:create",
    STUDY_WRONG: "game:studyWrong",
  },
  PLAYER: {
    SUCCESS_RECONNECT: "player:successReconnect",
    UPDATE_LEADERBOARD: "player:updateLeaderboard",
    JOIN: "player:join",
    LOGIN: "player:login",
    RECONNECT: "player:reconnect",
    LEAVE: "player:leave",
    SUBMIT_SENTENCE: "player:submitSentence",
    STUDY_SUBMIT: "player:studySubmit",
    STUDY_RESTART: "player:studyRestart",
    UPDATE: "player:update",
  },
  MANAGER: {
    SUCCESS_RECONNECT: "manager:successReconnect",
    CONFIG: "manager:config",
    GAME_CREATED: "manager:gameCreated",
    STATUS_UPDATE: "manager:statusUpdate",
    NEW_PLAYER: "manager:newPlayer",
    REMOVE_PLAYER: "manager:removePlayer",
    ERROR_MESSAGE: "manager:errorMessage",
    PLAYER_KICKED: "manager:playerKicked",
    AUTH: "manager:auth",
    RECONNECT: "manager:reconnect",
    LEAVE: "manager:leave",
    KICK_PLAYER: "manager:kickPlayer",
    START_GAME: "manager:startGame",
    ABORT_QUIZ: "manager:abortQuiz",
    NEXT_QUESTION: "manager:nextQuestion",
    SHOW_LEADERBOARD: "manager:showLeaderboard",
    GET_CONFIG: "manager:getConfig",
    LOGOUT: "manager:logout",
    UNAUTHORIZED: "manager:unauthorized",
    STUDY_PROGRESS: "manager:studyProgress",
    EXIT_GAME: "manager:exitGame",
    END_GAME_EARLY: "manager:endGameEarly",
    PLAY_AGAIN: "manager:playAgain",
    CHANGE_QUIZ: "manager:changeQuiz",
  },
  QUIZZ: {
    GET: "quizz:get",
    DATA: "quizz:data",
    SAVE: "quizz:save",
    SAVE_SUCCESS: "quizz:saveSuccess",
    UPDATE: "quizz:update",
    UPDATE_SUCCESS: "quizz:updateSuccess",
    DELETE: "quizz:delete",
    ERROR: "quizz:error",
  },
  RESULTS: {
    GET: "results:get",
    DATA: "results:data",
    DELETE: "results:delete",
  },
} as const

export const NO_TIME_LIMIT = -1

export const MEDIA_TYPES = {
  IMAGE: "image",
  VIDEO: "video",
  AUDIO: "audio",
} as const

export const EXAMPLE_QUIZZ = {
  subject: "ESL Sentence Builder - Example",
  questions: [
    {
      prompt: "그것은 큰 가스 덩어리야.",
      scrambledChunks: ["of gas.", "It", "a big ball", "is"],
      correctChunks: ["It", "is", "a big ball", "of gas."],
      correctSentence: "It is a big ball of gas.",
      cooldown: 5,
      time: 30,
    },
    {
      prompt: "나는 학교에 갑니다.",
      scrambledChunks: ["go", "I", "school.", "to"],
      correctChunks: ["I", "go", "to", "school."],
      correctSentence: "I go to school.",
      cooldown: 5,
      time: 30,
    },
    {
      prompt: "그녀는 빨간 사과를 좋아해요.",
      scrambledChunks: ["red apples.", "She", "likes"],
      correctChunks: ["She", "likes", "red apples."],
      correctSentence: "She likes red apples.",
      cooldown: 5,
      time: 30,
    },
  ],
} as const
