name: Docker Release
on:
  workflow_run:
    workflows: ["Bump Version on Release"]
    types:
      - completed

env:
  DOCKER_PLATFORMS: |
    linux/amd64
    linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract version and tags
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          # Extract major.minor (ex: 1.2.3 -> 1.2)
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1,2)
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV

      - name: Extract repository details (lowercase)
        run: |
          REPO_IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_IMAGE_NAME=$REPO_IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          version: latest
          install: true
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Log in to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ !env.ACT }}
          tags: |
            ghcr.io/${{ env.REPO_IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_IMAGE_NAME }}:${{ env.MAJOR_MINOR }}
            ghcr.io/${{ env.REPO_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
